CSE241: cse241
cse241: main.cpp AbstractBoard.cpp AbstractBoard.h BoardVector.cpp BoardVector.h BoardArray.cpp BoardArray.h BoardAdapter.cpp BoardAdapter.h 
	g++ -std=c++11 -c main.cpp
	g++ -std=c++11 -c AbstractBoard.cpp
	g++ -std=c++11 -c BoardVector.cpp
	g++ -std=c++11 -c BoardArray.cpp
	g++ -std=c++11 -c BoardAdapter.cpp
	g++ -std=c++11 -o output main.o AbstractBoard.o BoardVector.o BoardArray.o BoardAdapter.o
	./output
	
